# Generated by Django 5.2.17 on 2026-09-15 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('seo_text', models.TextField(blank=True, verbose_name='SEO-текст')),
                ('meta_title', models.CharField(blank=True, help_text='До 60 символов.', max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='До 160 символов.', max_length=200, verbose_name='Meta description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=300, unique=True, verbose_name='Старый путь')),
                ('new_path', models.CharField(max_length=300, verbose_name='Новый путь')),
            ],
            options={
                'verbose_name': 'редирект',
                'verbose_name_plural': 'редиректы',
                'ordering': ['old_path'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('model_code', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Цена, ₸')),
                ('show_price', models.BooleanField(default=False, verbose_name='Показывать цену')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('meta_title', models.CharField(blank=True, help_text='До 60 символов.', max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='До 160 символов.', max_length=200, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Характеристика')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.product')),
            ],
            options={
                'verbose_name': 'характеристика',
                'verbose_name_plural': 'характеристики',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
