# Generated by Django 5.2.17 on 2026-09-15 14:56

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Батыс Курылыс XXI', max_length=200, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, default='Казахстан, г. Астана, ул. Керей Жанибек хандар, 50/3', max_length=300, verbose_name='Адрес')),
                ('phones', models.TextField(blank=True, help_text='По одному номеру в строке.', verbose_name='Телефоны')),
                ('whatsapp_numbers', models.TextField(blank=True, default='+7 777 305 4243\n+7 777 377 3763', help_text='По одному номеру в строке.', verbose_name='WhatsApp')),
                ('notification_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для заявок')),
                ('public_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для клиентов')),
                ('working_hours', models.CharField(blank=True, help_text='Формат schema.org, например: Mo-Fr 09:00-18:00', max_length=200, verbose_name='Часы работы')),
                ('bin', models.CharField(blank=True, max_length=12, verbose_name='БИН')),
                ('map_url', models.URLField(blank=True, verbose_name='Ссылка на карту (2GIS)')),
            ],
            options={
                'verbose_name': 'настройки сайта',
                'verbose_name_plural': 'настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=catalog.models.product_image_path, verbose_name='Фото')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to=catalog.models.product_thumbnail_path)),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Alt-текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
