# Generated by Django 5.2.17 on 2026-09-16 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sitesettings_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_list',
            field=models.FileField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['xlsx', 'xls'])], verbose_name='Прайс-лист (Excel)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_list_updated',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Прайс обновлён'),
        ),
    ]
