# Generated by Django 5.2.17 on 2026-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_sitesettings_logo_sitesettings_price_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_verification',
            field=models.CharField(blank=True, default='iWvlBU0mWV3JhKvhVucYh0MaRMYU7Yk5sYp-d6hZsr8', help_text='Значение content из мета-тега google-site-verification в Search Console.', max_length=200, verbose_name='Код подтверждения Google'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_verification',
            field=models.CharField(blank=True, help_text='Значение content из мета-тега yandex-verification в Яндекс.Вебмастере.', max_length=200, verbose_name='Код подтверждения Яндекса'),
        ),
    ]
