# Generated by Django 5.2.17 on 2026-09-15 15:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_sitesettings_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Закрыта')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка менеджера')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Письмо отправлено')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название на момент заявки')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Количество')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='Товар')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.quoterequest')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
                'ordering': ['id'],
            },
        ),
    ]
